### ISSUE TITLE
 boundary-init job hangs

### ISSUE THREAD

**Issue by lucardcoder** [ugns/boundary-chart#23]
I am trying the helm chart you provided in EKS and it hangs at the boundary-init job. any idea why would that would be?
job Logs:
Error creating: pods “boundary-init-” is forbidden: error looking up service account boundary/boundary: serviceaccount “boundary” not found.
EKS Version: 1.26

**Comment by jbouse** [comment]
Hmm... let me take a look into this and see what's going on. I haven't looked at this chart in a while now, and it was before the EKS upgrade so might be something that needs to be updated.

**Comment by arogic** [comment]
Hi, I am having the same issue. It seems that the ServiceAccount doesn't get created. Regards

**Comment by lucardcoder** [comment]
there is a fix for that. you need to add below annotations to serviceaccount.yaml in templates:

  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"

**Comment by arogic** [comment]
Thanks @lucardcoder. I deployed the Service Account using the following Manifest, before deploying boundary with the helm chart to get around the issue.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boundary
  namespace: boundary
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: boundary
    meta.helm.sh/release-namespace: boundary
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
```

```bash
kubectl create namespace boundary
kubectl apply -f service_account.yaml
```

However, I am getting the following error on the pods:

```
Back-off restarting failed container boundary-controller-scale-down in pod boundary-init-dr6zn_boundary(421cb507-6ec5-4351-a9bd-b1bfee9de02c)
```

Any ideas?
